model_config: "configs/models/cnn.yaml"
dataset_config: "configs/datasets/cifar10.yaml"

seed: 42
device: "cuda"

# # 损失函数配置
# loss:
#   type: "cross_entropy"
#   reduction: "mean"
#   label_smoothing: 0.1
#   weight: 1.0

training:
  epochs: 50
  optimizer:
    type: "adamw"
    lr: 0.001
    weight_decay: 1e-5
  scheduler:
    type: CompositeLR
    step_frequency: epoch
    phases:
      # 预热阶段
      - scheduler_name: LinearWarmup
        config:
          warmup_epochs: 5
          warmup_start_factor: 0.1
        duration: 5
      
      # 阶梯式衰减阶段
      - scheduler_name: MultiStepLR
        config:
          milestones: [25, 40]  # 相对于此阶段的开始，即全局epoch的30、45
          gamma: 0.1
        duration: 45
  early_stopping:
    patience: 10
    min_delta: 0.001
    monitor: "loss"
    mode: "min"
  checkpoint:
    save_frequency: 5  # 每5个epoch保存一次权重
    # keep_num: 3  # 保留最近的3个checkpoint

# 钩子配置示例
hooks:
  - type: "TimeTrackingHook"
    name: "training_timer"
    frequency: 1  # 每个epoch都要触发
    
  - type: "FeatureMapHook"
    name: "feature_visualizer"
    frequency: 100  # 每100步可视化一次
    max_features: 16  # 每层最多显示16个特征图
    sample_batch_idx: 0  # 使用批次中的第一个样本
    
  - type: "GradientFlowHook"
    name: "gradient_visualizer"
    frequency: 200
    targets: ["conv1", "conv2", "conv3", "fc1", "fc2"]  # 要监视的模块
    
  - type: "SystemMonitorHook"
    name: "system_monitor"
    frequency: 50  # 每50步更新一次可视化（可根据需要调整）
    interval: 2  # 数据采集间隔（秒）
    track_cpu: true  # 是否监控CPU使用率
    track_memory: true  # 是否监控内存使用率
    track_gpu: true  # 是否监控GPU使用率
    track_gpu_memory: true  # 是否监控GPU内存使用率