dataset:
  type: "plate"
  data_name: "plate(3)"
  data_dir: "data"
  batch_size: 32
  num_workers: 4
  shuffle: true
  train_ratio: 0.8  # 训练集占总数据的比例
  transforms:
    resize: [224, 224]  # 调整图像大小为224x224
    center_crop: 224    # 可选的中心裁剪
    normalize:
      mean: [0.485, 0.456, 0.406]  # ImageNet预训练模型的标准均值
      std: [0.229, 0.224, 0.225]   # ImageNet预训练模型的标准差
